//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Uuu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Sdf.
    /// </summary>
    //  *** Start programmer edit section *** (Sdf CustomAttributes)

    //  *** End programmer edit section *** (Sdf CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SdfE", new string[] {
            "adf as \'Adf\'"})]
    [View("SdfL", new string[] {
            "adf as \'Adf\'"})]
    public class Sdf : ICSSoft.STORMNET.DataObject
    {
        
        private int fadf;
        
        //  *** Start programmer edit section *** (Sdf CustomMembers)

        //  *** End programmer edit section *** (Sdf CustomMembers)

        
        /// <summary>
        /// adf.
        /// </summary>
        //  *** Start programmer edit section *** (Sdf.adf CustomAttributes)

        //  *** End programmer edit section *** (Sdf.adf CustomAttributes)
        public virtual int adf
        {
            get
            {
                //  *** Start programmer edit section *** (Sdf.adf Get start)

                //  *** End programmer edit section *** (Sdf.adf Get start)
                int result = this.fadf;
                //  *** Start programmer edit section *** (Sdf.adf Get end)

                //  *** End programmer edit section *** (Sdf.adf Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Sdf.adf Set start)

                //  *** End programmer edit section *** (Sdf.adf Set start)
                this.fadf = value;
                //  *** Start programmer edit section *** (Sdf.adf Set end)

                //  *** End programmer edit section *** (Sdf.adf Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SdfE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SdfE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SdfE", typeof(IIS.Uuu.Sdf));
                }
            }
            
            /// <summary>
            /// "SdfL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SdfL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SdfL", typeof(IIS.Uuu.Sdf));
                }
            }
        }
    }
}
